accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('register/',views.register, name='register'),
    path('',views.home, name='home'),
    path('aboutus/',views.about_us, name='about_us'),
    path('contact/',views.contact, name='contact'),
]

appointment/urls.py
from django.urls import path
from . import views

app_name = 'appointment'

urlpatterns = [
    path("appointments/p/", views.AppointmentsForPatientView.as_view(), name="patient_appointments"),
    path("appointments/d/", views.AppointmentsForDoctorView.as_view(), name="doctor_appointments"),
    path("medHistory/", views.MedicalHistoryView.as_view(), name="med_history"),
    path("prescriptions/", views.PrescriptionListView.as_view(), name="doctor_prescriptions"),
    path("prescription/create", views.PrescriptionCreateView, name="doc_prescription_create"),
    path("appointment/create", views.AppointmentCreateView, name="appointment_create"),
    path("recdashboard/", views.recdashboard, name="rec_dashboard"),
    path("hrdashboard/", views.hrdashboard, name="hr_dashboard"),
]

hospital/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('accounts.urls', namespace='accounts')),
    path("", include('user_profile.urls', namespace='user_profile')),
    path("", include('appointment.urls', namespace='appointment')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

user_profile/urls.py
from django.urls import path
from . import views

app_name = "user_profile"

urlpatterns = [
    path('profile/', views.UpdatedUserProfile, name='profile'),
    path('profile/create/', views.CreateUserProfile, name='profile_create'),
    path('profile/<int:pk>/', views.UpdatedUserProfilePk, name='profile-pk'),
    path('profile/doc/<int:pk>/', views.UpdatedDocProfilePk, name='doc-profile-pk'),
    path('profile/<int:pk>/delete/', views.DeleteUserProfilePk, name='profile-delete'),
    path('profile/doc/<int:pk>/delete', views.DeleteDocProfilePk, name='doc-profile-delete'),
]

appointment/models.py
from django.db import models
from django.contrib.auth import get_user_model
User = get_user_model()

# Create your models here.

class Appointment(models.Model):
    date = models.DateField()
    time = models.TimeField()
    status = models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=10)
    patient = models.ForeignKey(User, on_delete=models.CASCADE, related_name='patient')
    doctor = models.ForeignKey(User, on_delete=models.CASCADE, related_name='doctor')
    
    def __str__(self):
        return "Patient - {} Doctor - {} at {} {}".format(self.patient, self.doctor, self.date, self.time)

class Prescription(models.Model):
    doctor = models.ForeignKey(User, on_delete=models.CASCADE, related_name='doctor_prescription')
    patient = models.ForeignKey(User, on_delete=models.CASCADE, related_name='patient_prescription')
    date = models.DateField(auto_now_add=True)
    symptoms = models.CharField(max_length=200)
    prescription = models.TextField()
    
    class Meta:
        ordering = ('-id',)
        
    def __str__(self):
        return "Prescription Doctor - {} Patient - {}".format(self.doctor, self.patient)

appointment/forms.py
from django import forms
from .models import *
from django.contrib.auth import get_user_model

User = get_user_model()

class DateInput(forms.DateInput):
    input_type = 'date'

class PrescriptionForm(forms.ModelForm):
    class Meta:
        model = Prescription
        fields = ('patient', 'symptoms', 'prescription')
    
    def __init__(self, *args, **kwargs):
        super(PrescriptionForm, self).__init__(*args, **kwargs)
        if self.instance:
            self.fields['patient'].queryset = User.objects.filter(user_type='P')


class AppointmentForm(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = '__all__'
        widgets = {
            'date': DateInput()
        }
    
    def __init__(self, *args, **kwargs):
        super(AppointmentForm, self).__init__(*args, **kwargs)
        if self.instance:
            self.fields['patient'].queryset = User.objects.filter(user_type='P')
            self.fields['doctor'].queryset = User.objects.filter(user_type='D')
            self.fields['date'].label = 'Date (DD-MM-YYYY)'
            self.fields['time'].label = 'Time 24 hr (HH:MM)'
    

appointment/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from user_profile.models import UserProfile
from .models import *
from .forms import *

# Create your views here.

class AppointmentsForPatientView(LoginRequiredMixin, ListView):
    login_url = '/login/'
    redirect_field_name = 'accounts:login'
    
    def get_queryset(self):
        return Appointment.objects.filter(patient=self.request.user)

class AppointmentsForDoctorView(LoginRequiredMixin, ListView):
    login_url = '/login/'
    redirect_field_name = 'accounts:login'
    
    def get_queryset(self):
        return Appointment.objects.filter(doctor=self.request.user)

class MedicalHistoryView(LoginRequiredMixin, ListView):
    login_url = '/login/'
    redirect_field_name = 'accounts:login'
    
    def get_queryset(self):
        return Prescription.objects.filter(patient=self.request.user)

class PrescriptionListView(LoginRequiredMixin, ListView):
    login_url = '/login/'
    redirect_field_name = 'accounts:login'
    
    def get_queryset(self):
        return Prescription.objects.filter(doctor=self.request.user)

@login_required(login_url='/login/')
def PrescriptionCreateView(request):
    if request.method == 'POST':
        form = PrescriptionForm(request.POST)
        if form.is_valid():
            prescription = form.save(commit=False)
            prescription.doctor = request.user
            prescription.save()
            return redirect('appointment:doctor_prescriptions')  
    else:
        form = PrescriptionForm()
    return render(request, 'appointment/prescription_create.html', {'form': form})     

@login_required(login_url='/login/')
def AppointmentCreateView(request):
    form_class = Appoin
    if request.method == 'POST':
        form = AppointmentForm(request.POST)
        if form.is_valid():
            appointment = form.save(commit=False)
            appointment.save()
            return redirect('appointment:rec_dashboard')
    else:
        form = AppointmentForm()
    return render(request, 'appointment/appointment_create.html', {'form': form})

@login_required(login_url = '/login/')
def recdashboard(request):
    if request.method == 'GET' and request.user.user_type == 'R':
        context = {
            'totalApp': len(Appointment.objects.all()),
            'compApp': len(Appointment.objects.filter(status='Completed')),
            'pendApp': len(Appointment.objects.filter(status='Pending')),
            'app_list': Appointment.objects.all(),
            'pat_list': UserProfile.objects.filter(user__user_type='P')[:5]
        }
        return render(request, 'appointment/rec_dashboard.html', context=context)

@login_required(login_url='/login/')
def hrdashboard(request):
    if request.method == "GET" and request.user.user_type == 'HR':
        context = {
            'totalPat': len(User.objects.filter(user_type='P')),
            'totalDoc': len(User.objects.filter(user_type='D')),
            'onDutyDoc': len(UserProfile.objects.filter(status='Active').filter(user__user_type='D')),
            'doc_list': UserProfile.objects.filter(user__user_type='D')
        }
        return render(request, 'appointment/hr_dashboard.html', context=context)

appointment/templates/appointment/appointment_create.html
{% extends 'base.html' %}
{% load bootstrap3 %}


{% block content %}
   <div class="container">
       <h2>Create an Appointment</h2>
       <form method="POST">
           {% csrf_token %}
           {% bootstrap_form form %}
           <input type="submit" value="Create" class="btn btn-primary">
       </form>
   </div> 
{% endblock %}
    

appointment/templates/appointment/appointment_list.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
    <div class="container">
        <h2>Your Appointments</h2>
        <div>
            {% if user.is_patient %}
                <table class="table table-striped">
                    <thead>
                        <th>Date</th>
                        <th>Time</th>
                        <th>Consulting Doctor</th>
                        <th>Status</th>
                    </thead>
                    
                    {% for obj in object_list %}
                    <tr>
                        <td>{{ obj.date }}</td>
                        <td>{{ obj.time }}</td>
                        <td>{{ obj.doctor }}</td>
                        <td>{{ obj.status }}</td>
                    </tr> 
                    {% endfor %}                       
                </table>
            {% endif %}

            {% if user.is_doctor %}
               <table class="table table-striped">
                   <thead>
                       <th>Date</th>
                       <th>Time</th>
                       <th>Patient Info</th>
                   </thead>
                   
                   {% for obj in object_list %}
                   <tr>
                       <td>{{ obj.date }}</td>
                       <td>{{ obj.time }}</td>
                       <td>{{ obj.patient }}</td>
                   </tr> 
                   {% endfor %}                      
               </table> 
            {% endif %}                
        </div>
    </div>
{% endblock %}
    

appointment/templates/appointment/hr_dashboard.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
    <div class="container">
        <h1 align="center">Dashboard</h1><br>
        <ul class="list-group">
            <li class="list-group-item">
                <strong>Total Doctors</strong> - {{ totalDoc }}
            </li>
            <li class="list-group-item">
                <strong>Total Patients</strong> - {{ totalPat }}
            </li>
            <li class="list-group-item">
                <strong>On Duty Doctors</strong> - {{ onDutyDoc }}
            </li>
        </ul>
    </div>

    <div class="row">
        <div class="col-md-12">
            <h3>Doctors</h3>
            <div class="card card-body">
                <table class="table table-striped">
                    <thead>
                        <th>Name</th>
                        <th>Phone</th>
                        <th>Email</th>
                        <th>Gender</th>
                        <th>Age</th>
                        <th>Status</th>
                        <th>Department</th>
                        <th>Salary</th>
                        <th>Update</th>
                        <th>Remove</th>
                    </thead>
                    
                    {% for obj in doc_list %}
                    <tr>
                        <td>{{ obj.name }}</td>
                        <td>{{ obj.phone }}</td>
                        <td>{{ obj.email }}</td>
                        <td>{{ obj.gender }}</td>
                        <td>{{ obj.age }}</td>
                        <td>{{ obj.status }}</td>
                        <td>{{ obj.department }}</td>
                        <td>{{ obj.salary }}</td>
                        <td><a href="{% url 'user_profile:doc-profile-pk' pk=obj.user.id %}"><button class="btn btn-warning">Update</button></a></td>
                        <td><a href="{% url 'user_profile:doc-profile-delete' pk=obj.user.id %}"><button class="btn btn-danger">Delete</button></a></td>
                    </tr>
                    {% endfor %}                       
                </table>
            </div>
        </div>
    </div>
{% endblock %}
    

appointment/templates/appointment/prescription_create.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
    <div class="container">
        <h2>Hello, {{ user.username }}</h2>
        <form method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" value="Create" class="btn btn-primary">
        </form>
    </div>
{% endblock %}
    

appointment/templates/appointment/prescription_list.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
    <div class="container">
        
        {% if user.is_patient %}
            <h2>Your Medical History</h2><br>
            <ul class="list-group">
                {% for obj in object_list %}
                <li class="list-group-item">
                    <h3><strong>{{ obj.date }}</strong></h3>
                    <p>Symptoms - {{ obj.symptoms }}</p>
                    <p>Prescription - {{ obj.prescription }}</p>
                    <p>Doctor - {{ obj.doctor }}</p>
                </li>
                {% endfor %}
            </ul>
        {% endif %}
        
        {% if user.is_doctor %}
            <h2>Your Prescriptions</h2>
            <a href="{% url 'appointment:doc_prescription_create' %}"><button class="btn btn-primary pull-right">Create New Prescription</button></a>
            <br><br>
            <ul class="list-group">               
                {% for obj in object_list %}
                <li class="list-group-item">
                    <h3><strong>{{ obj.date }}</strong></h3>
                    <p>Symptoms - {{ obj.symptoms }}</p>
                    <p>Prescription - {{ obj.prescription }}</p>
                    <p>Patient Name - {{ obj.patient}}</p>
                </li>
                {% endfor %}      
            </ul>
        {% endif %}
    </div>
{% endblock %}
    

appointment/templates/appointment/rec_dashboard.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
    <div class="container">
        <h1 align="center">Dashboard</h1><br>
        <ul class="list-group">
            <li class="list-group-item">
                <strong>Total Appointments</strong> - {{ totalApp}}
            </li>
            <li class="list-group-item">
                <strong>Appointments Done</strong> - {{ compApp }}
            </li>
            <li class="list-group-item">
                <strong>Upcoming Appointments</strong> - {{ pendApp }}
            </li>
        </ul>
    </div>

    <div class="row">
        <div class="col-md-10">
            <h3>Appointments</h3>
            <div class="card card-body">
                <a href="{% url 'appointment:appointment_create' %}"><button class="btn btn-primary">Create Appointment</button></a>
                <table class="table table-striped">
                    <thead>
                        <th>Date</th>
                        <th>Time</th>
                        <th>Doctor</th>
                        <th>Patient</th>
                        <th>Status</th>
                    </thead>
                    
                    {% for obj in app_list %}
                    <tr>
                        <td>{{ obj.date }}</td>
                        <td>{{ obj.time }}</td>
                        <td>{{ obj.doctor }}</td>
                        <td>{{ obj.patient }}</td>
                        <td>{{ obj.status }}</td>
                    </tr> 
                    {% endfor %}                      
                </table>
            </div>
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-10">
            <h3>Last 5 Patients</h3>
            <div class="card card-body">
                <a href="{% url 'user_profile:profile_create' %}"><button class="btn btn-primary">Create Patient</button></a>
                <table class="table table-striped">
                    <thead>
                        <th>Name</th>
                        <th>Phone</th>
                        <th>Email</th>
                        <th>Gender</th>
                        <th>Age</th>
                        <th>Update</th>
                        <th>Remove</th>
                    </thead>
                    
                    {% for obj in pat_list %}
                    <tr>
                        <td>{{ obj.name }}</td>
                        <td>{{ obj.phone }}</td>
                        <td>{{ obj.email }}</td>
                        <td>{{ obj.gender }}</td>
                        <td>{{ obj.age }}</td>
                        <td><a href="{% url 'user_profile:profile-pk' pk=obj.user.id %}"><button class="btn btn-warning">Update</button></a></td>
                        <td><a href="{% url 'user_profile:profile-delete' pk=obj.user.id %}"><button class="btn btn-danger">Delete</button></a></td>
                    </tr>   
                    {% endfor %}                       
                </table>
            </div>
        </div>
    </div>
{% endblock %}
    