accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('register/',views.register, name='register'),
    path('',views.home, name='home'),
    path('aboutus/',views.about_us, name='about_us'),
    path('contact/',views.contact, name='contact'),
]

appointment/urls.py
from django.urls import path
from . import views

app_name = 'appointment'

urlpatterns = [
    path("appointments/p/", views.AppointmentsForPatientView.as_view(), name="patient_appointments"),
    path("appointments/d/", views.AppointmentsForDoctorView.as_view(), name="doctor_appointments"),
    path("medHistory/", views.MedicalHistoryView.as_view(), name="med_history"),
    path("prescriptions/", views.PrescriptionListView.as_view(), name="doctor_prescriptions"),
    path("prescription/create", views.PrescriptionCreateView, name="doc_prescription_create"),
    path("appointment/create", views.AppointmentCreateView, name="appointment_create"),
    path("recdashboard/", views.recdashboard, name="rec_dashboard"),
    path("hrdashboard/", views.hrdashboard, name="hr_dashboard"),
]

hospital/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('accounts.urls', namespace='accounts')),
    path("", include('user_profile.urls', namespace='user_profile')),
    path("", include('appointment.urls', namespace='appointment')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

user_profile/urls.py
from django.urls import path
from . import views

app_name = "user_profile"

urlpatterns = [
    path('profile/', views.UpdatedUserProfile, name='profile'),
    path('profile/create/', views.CreateUserProfile, name='profile_create'),
    path('profile/<int:pk>/', views.UpdatedUserProfilePk, name='profile-pk'),
    path('profile/doc/<int:pk>/', views.UpdatedDocProfilePk, name='doc-profile-pk'),
    path('profile/<int:pk>/delete/', views.DeleteUserProfilePk, name='profile-delete'),
    path('profile/doc/<int:pk>/delete', views.DeleteDocProfilePk, name='doc-profile-delete'),
]

templates/base.html
<!DOCTYPE html>
{% load static %}

<html>
    <head>
        <title>Hospital</title>

        <!-- Latest compiled and minified CSS -->

        <link
        rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

        <!-- Optional theme -->
        <link
        rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

        <!-- Latest compiled and minified JavaScript -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


        <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    </head>

    <body>
        <nav class="navbar navbar-inverse" id="navbar" role="navigation">
            <div class="container">
                <a class="navbar-brand mynav" href="{% url 'accounts:home' %}">Hospital Management System</a>

                <ul class="nav navbar-nav navbar-right mynav">
                    {% if user.is_authenticated %}
                        
                        {% if user.is_doctor %}
                            <li><a href="{% url 'accounts:home' %}" class="btn btn-simple">Home</a></li>
                            <li><a href="{% url 'accounts:about_us' %}" class="btn btn-simple">About Us</a></li>
                            <li><a href="{% url 'accounts:contact' %}" class="btn btn-simple">Contact</a></li>
                            <li><a href="{% url 'user_profile:profile' %}" class="btn btn-simple">Profile</a></li>
                            <li><a href="{% url 'appointment:doctor_appointments' %}" class="btn btn-simple">Appointments</a></li>
                            <li><a href="{% url 'appointment:doctor_prescriptions' %}" class="btn btn-simple">Prescriptions</a></li>
                            <li><a href="{% url 'accounts:logout' %}" class="btn btn-simple"><button class="btn btn-warning">Log Out</button></a></li>
                            <p align="right" style="color:white">Welcome Dr. {{user.first_name }} {{user.last_name}}</p>
                        {% endif %}
                            
                        {% if user.is_patient %}
                            <li><a href="{% url 'accounts:home' %}" class="btn btn-simple">Home</a></li>
                            <li><a href="{% url 'accounts:about_us' %}" class="btn btn-simple">About Us</a></li>
                            <li><a href="{% url 'accounts:contact' %}" class="btn btn-simple">Contact</a></li>
                            <li><a href="{% url 'appointment:patient_appointments' %}" class="btn btn-simple">Your Appointments</a></li>
                            <li><a href="{% url 'user_profile:profile' %}" class="btn btn-simple">Profile</a></li>
                            <li><a href="{% url 'appointment:med_history' %}" class="btn btn-simple">Medical History</a></li>
                            <li><a href="{% url 'accounts:logout' %}" class="btn btn-simple"><button class="btn btn-warning">Log Out</button></a></li>
                            <p align="right" style="color:white">Welcome Patient, {{user.first_name }} {{user.last_name}}</p>
                        {% endif %}

                        {% if user.is_receptionist %}
                            <li><a href="{% url 'accounts:home' %}" class="btn btn-simple">Home</a></li>
                            <li><a href="{% url 'accounts:about_us' %}" class="btn btn-simple">About Us</a></li>
                            <li><a href="{% url 'accounts:contact' %}" class="btn btn-simple">Contact</a></li>
                            <li><a href="{% url 'appointment:rec_dashboard' %}" class="btn btn-simple">Dashboard</a></li>
                            <li><a href="{% url 'accounts:logout' %}" class="btn btn-simple"><button class="btn btn-warning">Log Out</button></a></li>
                            <p align="right" style="color:white">Welcome Receptionist, {{user.first_name }} {{user.last_name}}</p>
                        {% endif %}
                        
                        {% if user.is_HR %}
                            <li><a href="{% url 'accounts:home' %}" class="btn btn-simple">Home</a></li>
                            <li><a href="{% url 'accounts:about_us' %}" class="btn btn-simple">About Us</a></li>
                            <li><a href="{% url 'accounts:contact' %}" class="btn btn-simple">Contact</a></li>
                            <li><a href="{% url 'appointment:hr_dashboard' %}" class="btn btn-simple">Dashboard</a></li>
                            <li><a href="{% url 'accounts:logout' %}" class="btn btn-simple"><button class="btn btn-warning">Log Out</button></a></li>
                            <p align="right" style="color:white">Welcome HR, {{user.first_name }} {{user.last_name}}</p>
                        {% endif %}
                        
                    {% else %}
                            <li><a href="{% url 'accounts:home' %}" class="btn btn-simple">Home</a></li>
                            <li><a href="{% url 'accounts:about_us' %}" class="btn btn-simple">About Us</a></li>
                            <li><a href="{% url 'accounts:contact' %}" class="btn btn-simple">Contact</a></li>
                            <li><a href="{% url 'accounts:register' %}" class="btn btn-simple">Register</a></li>
                            <li><a href="{% url 'accounts:login' %}" class="btn btn-simple"><button class="btn btn-success">Log In</button></a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        <div class="container mycontent">
            
            {% block content %}
                
            {% endblock %}
                
        </div>
        <canvas id="canvas"></canvas>
    </body>

</html>